"""from template to first unit

Revision ID: f1c5053a785f
Revises: f2ee2fc0ff90
Create Date: 2024-05-28 19:12:12.517065

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1c5053a785f'
down_revision = 'f2ee2fc0ff90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threadmodel',
    sa.Column('thread_id', sa.Text(), nullable=False),
    sa.Column('user_fk', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_fk'], ['user.id'], name=op.f('fk_threadmodel_user_fk_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_threadmodel'))
    )
    op.add_column('chat', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('chat', sa.Column('last_activity', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user', sa.Column('balance', sa.BigInteger(), server_default='20000', nullable=False))
    op.alter_column('user', 'is_premium',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'language_code',
               existing_type=postgresql.ENUM('en', 'ru', 'UK', name='locales'),
               type_=sa.Text(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'language_code',
               existing_type=sa.Text(),
               type_=postgresql.ENUM('en', 'ru', 'UK', name='locales'),
               nullable=True)
    op.alter_column('user', 'is_premium',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('user', 'balance')
    op.drop_column('user', 'created_at')
    op.drop_column('chat', 'last_activity')
    op.drop_column('chat', 'created_at')
    op.drop_table('threadmodel')
    # ### end Alembic commands ###
